### ISSUE TITLE
如何路径不是默认的jeecg-boot，就扫描不出来

### ISSUE THREAD

**Issue by Jack-chen11** [MInggongK/jeecg-#2]
如何路径不是默认的jeecg-boot，希望能添加一个自定义路径的方式

**Comment by MInggongK** [comment]
关于你说的这个问题，我已经在readme说了，
对IWannaGetAll-v1.2.1工具，他用的几乎就是全jeecg-boot路径探测，所以导致很多漏洞扫不出来
我已经优化了其中的jeecg-boot-querySysUser漏洞
使用的就是抓取接口方式，非jeecg-boot目录，,这只是其中的一个漏洞
那么你想使用全漏洞都采取这种方法取探测非jeecg-boot路径的话，
那么我会同样会采取识别接口的方式，加入其他漏洞的判断方法，下个版本再发布吧

**Comment by MInggongK** [comment]
新版本已发布
